name: MasterDeploy CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Install Packages
        run: npm ci
      - name: Deploy to GH Pages
        run: |
          git config user.email ritoalpha1843@gmail.com
          git config user.name Cumbercubie
          git remote set-url origin https://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@github.com/Cumbercubie/cornydan-portfolio.git/
          npm run deploy
